name: craftfolio
description: "Personal portfolio site built with Flutter and Dart, showcasing my mobile development skills, projects, and experience. A hub for potential employers, collaborators, and clients to explore my work, contact me, and view my expertise in Flutter, Android, and more."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.8.1
  flutter_riverpod: ^2.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - .env