name: Deploy to GitHub Pages

on:
  push:
    branches:
      - stable  # Trigger deployment only when pushing to the stable branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'  # Specify your Flutter version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get
      # Step 4: Modify pubspec.yaml (for runtime configuration)
      - name: Modify pubspec.yaml
        run: |
          # Modify any part of pubspec.yaml file during deployment
          # Example: Disable the assets part that includes .env file
          sed -i 's|  - .env|#  - .env|' pubspec.yaml
          # You can add more modifications as per your requirements

      # Step 5: Set environment variables from GitHub secrets (to inject into the build process)
      - name: Set up environment variables
        run: echo "APIURL=${{ secrets.APIURL }}" >> $GITHUB_ENV && echo "ANONKEY=${{ secrets.ANONKEY }}" >> $GITHUB_ENV

      # Step 6: Update index.html (optional if needed)
      - name: Update index.html
        run: |
          sed -i 's|<base href="/">|<base href="/craftfolio/">|' web/index.html
          sed -i 's|<meta name="apple-mobile-web-app-capable" content="yes">|<meta name="mobile-web-app-capable" content="yes">|' web/index.html

      # Step 7: Build Flutter web (release)
      - name: Build Flutter web (release)
        run: flutter build web --release --base-href "/craftfolio/"
        env:
          APIURL: ${{ secrets.APIURL }}  # Inject the APIURL secret
          ANONKEY: ${{ secrets.ANONKEY }}  # Inject the ANONKEY secret

      # Step 8: Deploy to GitHub Pages (gh-pages branch)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to
          folder: build/web  # The folder to deploy
          token: ${{ secrets.TOKEN }}  # Authentication token
